export { CompletedPage } from './Completed'
export { GenericErrorPage } from './GenericError'
export { HomePage } from './Home'
export { MyDayPage } from './MyDay'
export { PlannedPage } from './Planned'
